### PR TITLE
Construct additional tests

### PR DESCRIPTION
**Pull request by brenns10**
I'm working on upping unit test coverage here.  Not ready for merge yet.

### CODE REVIEW

**Comment by brenns10** [comment]
This push has fix for #18.

**Comment by dealie16** [comment]
:+1:

**Comment by brenns10** [comment]
So, I merged from master and added a couple other tests.  What we're looking at right now is that I can continue writing tests on this branch and not merge, or we can merge this and put more tests on a new branch.  Since I've got fixes for a couple bugs in here, and since we may want to prioritize site generation over testing at this point in time, I think that we ought to merge this now.

**Comment by jpcjr** [comment]
:+1:

**Pull request merged**
