### PR TITLE
Competing session expiration pull request!

### PR DESCRIPTION
**Pull request by brenns10**
This just uses the default `SESSION_COOKIE_AGE` setting.  Not sure how that compares to @dealie16's solution, but it works fine on my machine (set it to something like 10 seconds to see the result).  I think the tests run fine with it too.

### CODE REVIEW

**Comment by brenns10** [comment]
resolves #71 as well

**Comment by dealie16** [comment]
I fixed mine to do it this way, but slightly different. The problem with this is that the cookie is only saved when it needs to be so you could be accessing a new page every 5 min for two hours straight and still get timed out.

**Comment by jpcjr** [comment]
Chiming in to confirm that I can reproduce Kyle's scenario.

**Comment by jpcjr** [comment]
Death to False Metal!!!

**Pull request closed without merging**
