### PR TITLE
Cleaned up some templates and changed the titles

### LINKED ISSUE #79: Title is wrong
It says "Corvid - Static Site Generator" while @jpcjr says it should say "Corvid - Static Site Generation Tool".

This is a P0 and should be fixed *immediately*.

### PR DESCRIPTION
**Pull request by dealie16**
I removed some unused templates and then changed the titles for some pages.

resolves #79

### CODE REVIEW

**Comment by brenns10** [comment]
I think there was a misunderstanding here.  I understood that issue to be about what goes in the `<title></title>` tags in the head.  Not what goes in the headings on the actual page.  I was just fine with the headings.  It just seemed like the actual title of the page (which is displayed in the title bar of the browser usually) should reflect what operation you're trying to do.

**Comment by brenns10** [comment]
The first commit seems great though.  If you were to revert the second one I'd be happy with that cleanup.  And if you were willing to change the `<title>`'s instead, that would be very exciting as well.

**Comment by dealie16** [comment]
Changed it to be the proper title

**Comment by brenns10** [comment]
Looks good :+1: :ship:

**Pull request merged**
