### PR TITLE
User manual

### PR DESCRIPTION
**Pull request by brenns10**
This adds a pretty darn simple user manual that walks you through creating a first project.  It also explains how to duplicate, delete, and download projects.  I also added a help link next to the logout link that goes directly to the user manual (the version hosted on GitHub Pages, so currently not updated with the user manual).

Tell me what you think about the content, I'm willing to add/update/revise.

### CODE REVIEW

**Comment by brenns10** [comment]
Resolves #75

**Comment by jpcjr** [comment]
Perhaps we could have an in-depth section including what is/isn't allowed in each form (e.g. usernames for User, project titles for Projects, Page Plugins for Pages/Post)? Especially for some potentially non-obvious stuff that are Corvid constructs.

**Comment by jpcjr** [comment]
I like what I see so far, though.

**Comment by dealie16** [comment]
:+1:  :shipit:

**Pull request merged**
