### PR TITLE
First Demo Functionality

### PR DESCRIPTION
**Pull request by jpcjr**
Unfortunately, I had to add a non-default field to the Project model, so you'll need to recreate the database.

It's rough, but it works. Please play with this branch and send suggestions.

@dealie16 @brenns10

### CODE REVIEW

**Comment by brenns10** [comment]
Do you have some data I can use for a default theme?  I keep getting an error when Django tries to import the `CreateProjectView`, in the line where you set `default_theme = Theme.objects.get(title='default')`.  Should I just create one in the admin backend?

**Comment by jpcjr** [comment]
`python manage.py populate`

**Comment by brenns10** [comment]
Works on my machine!

**Comment by brenns10** [comment]
:+1:

**Pull request merged**
