### PR TITLE
Project plugins

### PR DESCRIPTION
**Pull request by jpcjr**
To do this:
- default theme needs to point to a modified version of the default. Purge all your themes, then run the newly-merged populate/loadthemes command!
- we now add themes selectively to the `themes` folder instead of cloning from pelican-themes. Otherwise, project plugins are impossible. (Or, at least, unnecessarily janky.)

### CODE REVIEW

**Comment by jpcjr** [comment]
Please don't merge; I still need to add tests!!!

**Comment by brenns10** [comment]
You have my sincere apologies on the merge conflicts.  Things you may need to worry about:

- In the project home template, make sure the "delete project" link stays gone.
- My tests in `test_cloning.py` depend on being able to create and update project plugins.  It doesn't look like any of the changes you made will break that, but keep it in mind.

**Comment by jpcjr** [comment]
Looks like we're good. Merge?

**Comment by brenns10** [comment]
I'm just going to pull and make sure UI changes held, and take things for a test drive.  But for the most part I trust your project plugin stuff :)

**Comment by brenns10** [comment]
I approve, :ship: :it:

**Pull request merged**
