### PR TITLE
Add a nifty jumbotron to the login page.

### LINKED ISSUE #43: Home Page
Adding a Splash Screen with some basic info for prospective users would make our site seem friendlier.

### PR DESCRIPTION
**Pull request by brenns10**
Resolves #43

### CODE REVIEW

**Comment by brenns10** [comment]
Contents suggestions are very welcome.

**Comment by jpcjr** [comment]
How about "Website generation made easy"?

1. It's terse.
2. Our users aren't average; they're extraordinary for choosing our service ;)

**Comment by jpcjr** [comment]
Other than phrasing, :+1: and merge from me!

**Comment by jpcjr** [comment]
```
oh wait

"Websites made easy"

literally!!!!
```

**Comment by jpcjr** [comment]
hmm... I think the header could stand to go up a size. Yay or nay?

**Comment by brenns10** [comment]
Sorry, did not see this comment.  I'm pretty satisfied with the header.  If it goes any bigger, it will cause the header to wrap within the jumbotron, which looks pretty nasty.  I'm just gonna merge it :)

**Pull request merged**
