### PR TITLE
Page plugins

### LINKED ISSUE #68: Page Plugins
- [ ] Link to create them in the Project home
- [ ] Add checkbox to CrUpdate Post (/Page?) to select plugins

### PR DESCRIPTION
**Pull request by jpcjr**
At long last, Page Plugins! Resolves #68 

### Limitations
- When editing Pages/Posts, active plugins are not automatically checked. (They
  are being saved properly, though.) It sucks for UX, but it's not a hard show-stopper
  and I don't know how to fix it. Any suggestions working with a
  `ModelMultipleChoiceField` @brenns10?

- We don't actually add head markup to the head; we're actually sticking it in
  the body before the body markup because sticking things in the head would
  require article metadata in the context. In theory, this *should* work, but
  it's misleading and suboptimal. There might be a way out of this using files, but
  I want this functionality shipped first.

### CODE REVIEW

**Comment by jpcjr** [comment]
Hmm...  Travis seems to be breaking because of a migration issue. Would you mind scoping it out @brenns10?

The tests were passing when I pushed it, so I was expecting a pass here (and I would expect the same on everyone else's computers.)

**Comment by dealie16** [comment]
@jpcjr it is failing when I check it because removed the import for get_object_or_404 in views/post.py

**Comment by jpcjr** [comment]
Travis is failing because of a migration issue, so that's not it. The tests were fine on the original commit. I just tried removing imports and committing to see if it worked itself out, but I messed up.

**Comment by brenns10** [comment]
I think the migrations are broken because you hadn't applied the latest migration before running `makemigrations`.  So now there are two migrations, both numbered 17.  I have no idea what to do about that.

**Comment by dealie16** [comment]
I think I might have fixed it one sec

**Comment by brenns10** [comment]
Well, just looking at the Travis output, doing something like `python manage.py makemigrations --merge` might fix it.

**Comment by jpcjr** [comment]
I tried merging the migrations. If that fails, we could just edit them by hand. Though, I'll wait to see what Kyle has.

**Comment by dealie16** [comment]
okay fixed it in my PR should I push my commit to this PR or just use the other PR?

**Pull request closed without merging**
