### PR TITLE
Added validation to Project.title and User.username

### PR DESCRIPTION
**Pull request by dealie16**
Adding the validation to username is a bit weird.

### CODE REVIEW

**Comment by brenns10** [comment]
What validation needs to be added to the username?  Are there any username strings that break links?  I thought Jeff and I tested out the username requirements, and they were pretty solid already.

**Comment by dealie16** [comment]
For some reason I thought we talked about applying this to usernames too, I can remove that.

**Comment by brenns10** [comment]
I think usernames are fine; so probably remove that.  However, the other stuff looks good.  I like that it looks like you've consolidated validation for project titles into a single function - much cleaner.

**Comment by brenns10** [comment]
With your change :+1: :shipit:

**Pull request merged**
