### PR TITLE
Site generation view

### PR DESCRIPTION
**Pull request by jpcjr**
1-click site content -> zip. Comes with several limitations, namely:
- repeated requests to download a site, malicious or otherwise, generates a new zip & downloads.
  + also doesn't save previous / most recent Zip. Might not be a bad item.
- can't use Chrome's `file://` to explore sites. Need a simple server, like:
```
python3 -m http.server --bind 'localhost' 9001
```

### CODE REVIEW

**Comment by jpcjr** [comment]
@brenns10

**Comment by brenns10** [comment]
dis shit is sexy yo

**Comment by brenns10** [comment]
:love_hotel: :cupid: :heart: :heart_eyes_cat:

**Comment by brenns10** [comment]
hawt :hotsprings:

**Comment by brenns10** [comment]
:heart: :+1: :ship: :it: :shipit:

**Pull request merged**
