### PR TITLE
Page plugins fix

### PR DESCRIPTION
**Pull request by dealie16**
I am going to try this fix now. Didn't add my commit :cry:
Fix:
* Rebased on master
* merged migrations

### CODE REVIEW

**Comment by jpcjr** [comment]
Awesome. :100:

Anything else about page plugins anyone would like to say?

(Resolves #68)

**Comment by brenns10** [comment]
I have narrowed down the cause of the form for Pages and Posts not displaying the existing plugins linked with the Page/Post when you edit.  It seems that the `forms.CheckboxSelectMultiple` widget doesn't actually display the initial value.  This may be a bug in Django, or it could be some undocumented incantation that we aren't aware of.  When I removed the `widget=forms.CheckboxSelectMultiple()` argument of the `ModelMultipleChoiceField` constructor, it reverted back to a listbox widget that correctly displays the existing values.  While control-clicking a listbox widget isn't the most intuitive UX, it's a lot better than checkboxes that don't load initial values properly.  I can push a commit with this fix if you'd like.

**Comment by jpcjr** [comment]
I'm wondering if it has to do with how I initialize the field as a class variable (esp. with the empty queryset.) This really bugs me though.

IMO, I think the listbox widget is less intuitive than the checkboxes (because you need to press control to check/uncheck a single plugin.) Perhaps we could list active Page Plugins at the bottom of the view and keep the checkboxes? If you think that's worse, then perhaps we can go with the listbox.

**Comment by brenns10** [comment]
I think that's worse: if I'm a user, and I click Edit, but make no changes, I expect that I could click save and nothing would change.  The most unintuitive behavior imaginable would be that my plugins are automatically dropped out of the page unless I remember to re-check them.

I have some commits on my local copy of the branch (which I will push up here now) that do a number of things:

- Go back to the listbox.
- Add help texts to the listbox so that people know how to multiple select.
- Move the plugin listbox above the content pane (this was a judgement call and if we don't like it I'll revert it)
- Put the page/plugin forms inside the forms module (they're complex enough to go there now).

I think the help texts I've added make the listbox just as good as the checkboxes.

**Comment by jpcjr** [comment]
Ah, didn't think of the "just editing" case. Listboxes are wayyy better than checkbox + list there.

Push your commits they're ready.

**Comment by brenns10** [comment]
I already pushed my commits.  I think the only question is whether we want to keep the plugins above the content as I have it now.  I guess I'm fine with it either way, I just figured that having the dynamically expanding preview pane being at the very bottom makes the most sense.

**Comment by jpcjr** [comment]
I say it's fine. :hear_no_evil: :ship:

**Pull request merged**
